language: node_js

node_js:
  - "12"

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

branches:
  only:
  - master

install:
  - npm install
  - npm run webpack

cache:
  directories:
    - node_modules

git:
  depth: 1